In [28]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [29]:
df=pd.read_excel('/content/Supermarket_Sales_Data.xlsx')
df

,Invoice ID,Branch,Customer Type,Gender,Product Line,Unit Price,Quantity,Tax 5%,Total,Date,Payment,Gross Income
0,INV1000,A,Normal,Female,Food and beverages,63.45,4.0,13.38,218.50,2024-04-01,Credit card,32.26
1,INV1001,B,Normal,Male,Fashion accessories,43.23,3.0,8.00,78.51,2024-04-01,Credit card,46.34
2,INV1002,C,Member,Female,Home and lifestyle,50.88,NaN,17.42,106.95,2024-04-01,Credit card,21.30
3,INV1003,B,Member,Female,Food and beverages,59.37,1.0,9.99,346.94,01/02/2024,Ewallet,37.66
4,INV1004,B,Member,Female,Fashion accessories,59.40,NaN,19.40,107.09,2024/03/01,Ewallet,45.25
...,...,...,...,...,...,...,...,...,...,...,...,...
295,INV1295,A,Normal,Female,Fashion accessories,82.67,4.0,11.24,160.55,2024-01-01,Cash,27.42
296,INV1296,C,Normal,Male,Home and lifestyle,96.59,2.0,6.91,490.39,01/02/2024,Credit card,23.30
297,INV1297,A,Normal,Female,Sports and travel,81.10,NaN,12.60,308.90,2024-04-01,Ewallet,47.89
298,INV1298,C,Normal,Female,Food and beverages,72.15,3.0,14.61,299.56,2024-01-01,Ewallet,28.51
299,INV1299,C,Member,Male,Home and lifestyle,56.92,1.0,6.18,379.08,2024-04-01,Ewallet,14.86

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Invoice ID     300 non-null    object
 1   Branch         300 non-null    object
 2   Customer Type  300 non-null    object
 3   Gender         300 non-null    object
 4   Product Line   300 non-null    object
 5   Unit Price     300 non-null    float64
 6   Quantity       232 non-null    float64
 7   Tax 5%         300 non-null    float64
 8   Total          300 non-null    float64
 9   Date           300 non-null    object
 10  Payment        300 non-null    object
 11  Gross Income   266 non-null    float64
dtypes: float64(5), object(7)
memory usage: 28.3+ KB

In [31]:
df.describe()

       Unit Price    Quantity      Tax 5%       Total  Gross Income
count  300.000000  232.000000  300.000000  300.000000    266.000000
mean    56.604200    2.465517   10.496167  256.421633     28.889286
std     24.827795    1.080573    5.520405  139.948888     13.015180
min     10.210000    1.000000    1.090000   25.300000      5.100000
25%     36.835000    2.000000    5.622500  129.310000     17.552500
50%     57.770000    2.000000   10.560000  262.090000     30.250000
75%     77.822500    3.000000   14.907500  373.940000     39.597500
max     99.790000    4.000000   19.990000  498.410000     49.980000

In [32]:
df['Branch']=df['Branch'].str.strip().str.title()

In [33]:
df['Branch'].value_counts()

Branch
A    121
C     98
B     81
Name: count, dtype: int64

In [34]:
df['Customer Type']=df['Customer Type'].str.strip().str.title()

In [35]:
df['Customer Type'].value_counts()

Customer Type
Normal    164
Member    136
Name: count, dtype: int64

In [51]:
df['Date'].value_counts()

Date
2024-01-02    78
2024-04-01    77
2024-01-01    73
2024-03-01    72
Name: count, dtype: int64

In [50]:
df['Date']=pd.to_datetime(df['Date'],format='mixed')
df['Date'] = df['Date'].dt.strftime('%Y-%m-%d')

In [63]:
df.isna().sum()

Invoice ID       0
Branch           0
Customer Type    0
Gender           0
Product Line     0
Unit Price       0
Quantity         0
Tax 5%           0
Total            0
Date             0
Payment          0
Gross Income     0
dtype: int64

In [71]:
df['Quantity'].fillna(df['Quantity'].median(),inplace=True)

/tmp/ipykernel_15051/549334851.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Quantity'].fillna(df['Quantity'].median(),inplace=True)

In [72]:
df['Gross Income'].fillna(df['Gross Income'].median(),inplace=True)

/tmp/ipykernel_15051/1062684649.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Gross Income'].fillna(df['Gross Income'].median(),inplace=True)

In [73]:
df.isna().sum()

Invoice ID       0
Branch           0
Customer Type    0
Gender           0
Product Line     0
Unit Price       0
Quantity         0
Tax 5%           0
Total            0
Date             0
Payment          0
Gross Income     0
dtype: int64

In [74]:
df['Total']=df['Unit Price']*df['Quantity']

In [52]:
df['Gender']=df['Gender'].str.strip().str.title()

In [53]:
df['Gender'].value_counts()

Gender
Male      159
Female    141
Name: count, dtype: int64

In [84]:
df.columns = (df.columns.str.strip().str.lower().str.replace(r'[^a-z0-9]+', '_', regex=True))

In [79]:
from google.colab import files

In [85]:
df.to_csv("supermarket_sales.csv",index=False, sep=',')

In [86]:
files.download('supermarket_sales.csv')